server:
  port: 8080
spring:
  application:
    name: metro-backend
  datasource:
    url: jdbc:mysql://localhost:8889/metro_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true